import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {
  const { locale } = useRouter();

  const [translations, setTranslations] = useState({});

  useEffect(() => {
    const loadTranslations = async () => {
      const loadedTranslations = await import(`../public/locales/${locale}/home.json`);
      setTranslations(loadedTranslations);
    };
    loadTranslations();
  }, [locale]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
      >
        <h2>{translations.welcomeMessage}</h2>
      </div>
    </>
  );
}
